#ifndef __i386__
#ifdef _ARM_ARCH_7
#include <arm/arch.h>
# GENERATED CODE - DO NOT EDIT"
# This file was generated by /Users/oliver/Development/trash/plblockimp/Other Sources/gentramp.sh on Sat Mar 22 21:49:09 CET 2014

# Write out the trampoline table, aligned to the page boundary
.text
.align 12
.globl _aspects_forwarding_trampoline_stret_page

_aspects_forwarding_trampoline_stret_page:
_aspects_forwarding_trampoline_stret:
sub r12, #0x1000        // r12 = r12 - 4096, that is where the data for this trampoline is stored
ldr r2, [r12, #-4]      // load r2, which holds SEL _cmd, with the selector stored for this trampoline
ldr r12, [r12, #-8]     // the pointer to objc_msgSend is stored with an offset of 8
bx r12                  // branch directly to r12, which now contains the address to objc_msgSend

// branching is done by jumping to a calculated offset at link time.
// therefore, `b _objc_msgSend` does not work for trampolines because the calculated offset will be wrong after remapping the trampoline page with vm_remap

# Save pc+8 into r12, then jump to the actual trampoline implementation
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;

# Next trampoline entry point
mov r12, pc
b _aspects_forwarding_trampoline_stret;
#endif
#endif
